routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    $data = array();
    return view('frontend.index', $data);
})->name('home');

Route::get('inscripcion', 'InscripcionController@showFrontEnd')->name('inscripcion');
Route::post('inscripcion/save_and_pay', 'InscripcionController@saveAndPay')->name('saveAndPay');
Route::get('inscripcion/{codigo_persona}/transaccion', 'InscripcionController@transaccion')->name('transaction');
\
Route::get('/mailable', function() {
    $participant = App\Models\Persona::findOrFail(4);
    return (new App\Notifications\RegistroNotification($participant))->toMail($participant);
});

//Move from /home to /admin/dashboard
Route::middleware(['auth'])->group(function() {
    Route::redirect('/home', '/admin/dashboard');
});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function() {
    // Login
    Route::resource('/', 'Auth\LoginController');

    // Dashboard
    Route::resource('dashboard', 'DashboardController');

    // Iglesia
    Route::resource('iglesia', 'IglesiaController');

    // Usuario
    Route::resource('usuario', 'UsuarioController');

    // Referencia
    Route::resource('referencia', 'ReferenciaController');

    // Inscripcion
    Route::resource('inscripcion', 'InscripcionController');
    Route::get('/inscripcion/{anio}/list', 'InscripcionController@list')->name('listaPersonas');
    Route::get('/inscripcion/{id}/persona', 'InscripcionController@showDetail')->name('personaDetail');
    Route::post('/inscripcion/persona/pagada', 'InscripcionController@markAsPaid')->name('personaPagada');
    Route::post('/inscripcion/persona/voluntario', 'InscripcionController@markAsVolunteer')->name('personaVoluntaria');
    Route::post('/inscripcion/confirmation/resend', 'InscripcionController@resendPaymentInformation')->name('resendConfirmation');

    // Import/Export Data
    Route::name('excel.')->group(function () {
        Route::get('export_all', 'ExcelManagerController@exportAll')->name('export');
    });
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Utilities\Helpers;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public $data;

    public function __construct() {
        $this->data['pageTitle'] = 'Dashboard';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['helper'] = new Helpers();
        $this->data['registros_por_usuario'] = User::all();

        return view('backend.dashboard.show', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/dashboard/show.blade.php
@extends('backend.layout.mainlayout')
 
@section('content')
    <div class="container-fluid">
        <div class="row">
            
            @include('backend.layout.menu')
                    
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Dashboard</h1>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h4>Estadísticas Conferencia | <small class="text-muted"> Informaciones actuales.</small></h4>
                            </div>
                            <table id="example" class="table table-hover w-100">
                                <thead>
                                    <tr>
                                        <th class="text-left">Dato</th>
                                        <th class="text-center">Valor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Total de personas inscritas: </td>
                                        <td class="text-center">{{ $helper->totalPersonasInscritas() }}</td>
                                    </tr>
                                    <tr>
                                        <td>Total de ayudantes: </td>
                                        <td class="text-center">{{ $helper->totalAyudantes() }}</td>
                                    </tr>
                                    <tr>
                                        <td>Total de mujeres:</td>
                                        <td class="text-center">{{ $helper->totaPersonasPorTipo('genero', 'F') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Total de hombres: </td>
                                        <td class="text-center">{{ $helper->totaPersonasPorTipo('genero', 'M') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Total de Asistencias Nacionales: </td>
                                        <td class="text-center">{{ $helper->totaPersonasPorTipo('pais', 'República Dominicana') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Total de Asistencias Internacionales:</td>
                                        <td class="text-center">{{ $helper->totaPersonasPorTipo('pais', 'República Dominicana', '!=') }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h4>Estadísticas Conferencia | <small class="text-muted"> Informaciones año pasado.</small></h4>
                            </div>
                            <table id="example" class="table table-hover w-100">
                                <thead>
                                    <tr>
                                        <th class="text-left">Dato</th>
                                        <th class="text-center">Valor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Total de personas inscritas: </td>
                                        <td class="text-center">344</td>
                                    </tr>
                                    <tr>
                                        <td>Total de ayudantes: </td>
                                        <td class="text-center">16</td>
                                    </tr>
                                    <tr>
                                        <td>Total de mujeres:</td>
                                        <td class="text-center">183</td>
                                    </tr>
                                    <tr>
                                        <td>Total de hombres: </td>
                                        <td class="text-center">161</td>
                                    </tr>
                                    <tr>
                                        <td>Total de Asistencias Nacionales: </td>
                                        <td class="text-center">339</td>
                                    </tr>
                                    <tr>
                                        <td>Total de Asistencias Internacionales:</td>
                                        <td class="text-center">5</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <br>
                
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h4>Desglose de Inscripciones | <small class="text-muted"> Informaciones actuales la plataforma.</small></h4>
                            </div>
                            <table id="example" class="table table-hover w-100">
                                <thead>
                                    <tr>
                                        <th width="80%">Punto de Venta</th>
                                        <th width="20%"># Inscripciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($registros_por_usuario as $usuario)
                                        <tr>
                                            <td>{{ $usuario->name }}</td>
                                            <td class="text-center">{{ $usuario->registrosAsociados()->where('codigo_registro', 'LIKE', $helper->getAnioActual().'%')->count() }}</td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td class="text-center" colspan="2">No hay personas registradas.</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h4>Descarga de Reportes | <small class="text-muted"> Excel con las informaciones al día.</small></h4>
                            </div>
                            <table id="example" class="table table-hover w-100">
                                <thead>
                                    <tr>
                                        <th width="80%">Reporte</th>
                                        <th width="20%">Descarga</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Inscripciones a la fecha</td>
                                        <td>
                                            <a href="{{ route('admin.excel.export') }}" type="button" class="btn btn-sm btn-info btn-fill">Descargar</a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
@endsection

@section('content_custom_js')
    <script src="//code.jquery.com/jquery-3.3.1.js"></script>
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
@endsection