routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    $data = array();
    return view('frontend.index', $data);
})->name('home');

Route::get('inscripcion', 'InscripcionController@showFrontEnd')->name('inscripcion');
Route::post('inscripcion/save_and_pay', 'InscripcionController@saveAndPay')->name('saveAndPay');
Route::get('inscripcion/{codigo_persona}/transaccion', 'InscripcionController@transaccion')->name('transaction');
\
Route::get('/mailable', function() {
    $participant = App\Models\Persona::findOrFail(4);
    return (new App\Notifications\RegistroNotification($participant))->toMail($participant);
});

//Move from /home to /admin/dashboard
Route::middleware(['auth'])->group(function() {
    Route::redirect('/home', '/admin/dashboard');
});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function() {
    // Login
    Route::resource('/', 'Auth\LoginController');

    // Dashboard
    Route::resource('dashboard', 'DashboardController');

    // Iglesia
    Route::resource('iglesia', 'IglesiaController');

    // Usuario
    Route::resource('usuario', 'UsuarioController');

    // Referencia
    Route::resource('referencia', 'ReferenciaController');

    // Inscripcion
    Route::resource('inscripcion', 'InscripcionController');
    Route::get('/inscripcion/{anio}/list', 'InscripcionController@list')->name('listaPersonas');
    Route::get('/inscripcion/{id}/persona', 'InscripcionController@showDetail')->name('personaDetail');
    Route::post('/inscripcion/persona/pagada', 'InscripcionController@markAsPaid')->name('personaPagada');
    Route::post('/inscripcion/persona/voluntario', 'InscripcionController@markAsVolunteer')->name('personaVoluntaria');
    Route::post('/inscripcion/confirmation/resend', 'InscripcionController@resendPaymentInformation')->name('resendConfirmation');

    // Import/Export Data
    Route::name('excel.')->group(function () {
        Route::get('export_all', 'ExcelManagerController@exportAll')->name('export');
    });
});

resources/views/backend/layout/mainlayout.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        @include('backend.layout.partials.head')
    </head>
    <body>
        {{-- Nav Section --}}
        @include('backend.layout.partials.nav')  
        
        {{-- Header Section --}}
        @include('backend.layout.partials.header')

        {{-- Content Section --}}
        @yield('content')

        {{-- Footer Section --}}
        @include('backend.layout.partials.footer')        

        {{-- Footer Scripts Section --}}
        @include('backend.layout.partials.footer-scripts')
        
        {{-- Content Scripts --}}
        @yield('content_custom_js')
        @yield('content_custom_js_table')
    </body>
</html>

resources/views/backend/layout/menu.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.dashboard') === 0) ? 'active' : '' }}" href="{{ route('admin.dashboard.index') }}">
                    <span data-feather="bar-chart-2"></span>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Operaciones Conferencia</span>
            <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
            </a>
        </h6>
        <ul class="nav flex-column">
           <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.inscripcion.create') === 0) ? 'active' : '' }}" href="{{ route('admin.inscripcion.create') }}">
                    <span data-feather="fast-forward"></span>
                    Registrar Personas <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.inscripcion.index') === 0) ? 'active' : '' }}" href="{{ route('admin.inscripcion.index') }}">
                    <span data-feather="list"></span>
                    Ver Personas
                </a>
            </li>
        </ul>
        
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Administración Webite</span>
            <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
            </a>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.page') === 0) ? 'active' : '' }}" href="#">
                    <span data-feather="file-text"></span>
                    Iglesias
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.carousel') === 0) ? 'active' : '' }}" href="#">
                    <span data-feather="box"></span>
                    Roles
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.video') === 0) ? 'active' : '' }}" href="#">
                    <span data-feather="video"></span>
                    Ciudades
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.blog') === 0) ? 'active' : '' }}" href="#">
                    <span data-feather="book"></span>
                    Blog
                </a>
            </li>
            <li class="nav-item d-none">
                <a class="nav-link" href="#">
                    <span data-feather="aperture"></span>
                    Países
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.data') === 0) ? 'active' : '' }}" href="#">
                    <span data-feather="sliders"></span>
                    Motivos
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.referencia') === 0) ? 'active' : '' }}" href="{{ route('admin.referencia.index') }}">
                    <span data-feather="git-branch"></span>
                    Referencias
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ (strpos(Route::currentRouteName(), 'admin.usuario') === 0) ? 'active' : '' }}" href="{{ route('admin.usuario.index') }}">
                    <span data-feather="user"></span>
                    Usuarios
                </a>
            </li>
        </ul>
    </div>
</nav>